#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

"""
Example output from special agent:
<<<cloudflare_status_api>>>
id name status group_id group components(if any)
38w9dn5m8n4p Tianjin,_China_-_(TSN) operational 77867vxkttgw False None

Example of string_table input for parsing
[['38w9dn5m8n4p','Tianjin,_China_-_(TSN)','operational','77867vxkttgw','False','None'],]
"""

from .agent_based_api.v1 import *

def parse_cloudflare_status_api(string_table):
    parsed = []
    for site in string_table:
        site_dict = {}
        site_dict["id"] = site[0]
        site_dict["name"] = modify_strings(site[1])
        site_dict["status"] = site[2]
        site_dict["group_id"] = site[3]
        site_dict["group"] = site[4]
        site_dict["components"] = site[5]
        parsed.append(site_dict)
    return parsed


def modify_strings(data):
    if isinstance(data, str):
        mod_data = data.replace("!", "’")
        return mod_data.replace("_"," ")
    else:
        return data


def discovery_cloudflare_status_api(parsed):
    for site in parsed:
        # filter for the group
        if site["group_id"] == "1km35smx8p41" or site["group"] == 'True':
            yield Service(item=site["name"])


def check_cloudflare_status_api(item, params, parsed):
    # default to Unknown
    exit_code = state.OK
    # Notify if empty parsed input
    if parsed == []:
        yield Result(
            state.CRIT,
            summary='No pool data available'
        )
    # Filter on the item passed and exit_code
    else:
        for site in parsed:
            if site["name"] == item:
                output = f'{site["name"]}'
                if site["status"] == "operational":
                    output += ' is fully operational.'
                    exit_code = state.OK
                elif site["status"] == "partial_outage":
                    output +=  ' is in a partial outage.'
                    exit_code = state.WARN
                elif site["status"] == "degraded_performance":
                    output +=  ' is experiencing degraded performance.'
                    exit_code = state.WARN
                else:
                    output +=  ' is in an unidentified or critical state.'
                    exit_code = state.CRIT
        yield Result(
            state=exit_code,
            summary=output,
            details='detailed output'
        )

register.check_plugin(
    name = "cloudflare_status_api",
    service_name = "Cloudflare Service %s",
    discovery_function = discovery_cloudflare_status_api,
    check_function = check_cloudflare_status_api,
    parse_function = parse_cloudflare_status_api,
)