#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

"""
Example output from special agent:
<<<cloudflare_status_api>>>
id name status group_id group components(if any)
38w9dn5m8n4p Tianjin,_China_-_(TSN) operational 77867vxkttgw False None

Example of string_table input for parsing
[['38w9dn5m8n4p','Tianjin,_China_-_(TSN)','operational','77867vxkttgw','False','None'],]
"""


def parse_cloudflare_status_api(string_table):
    parsed = []
    for site in string_table:
        site_dict = {}
        site_dict["id"] = site[0]
        site_dict["name"] = modify_strings(site[1])
        site_dict["status"] = site[2]
        site_dict["group_id"] = site[3]
        site_dict["group"] = site[4]
        site_dict["components"] = site[5]
        parsed.append(site_dict)
    return parsed


def modify_strings(data):
    if isinstance(data, str):
        mod_data = data.replace("!", "’")
        return mod_data.replace("_"," ")
    else:
        return data


def discovery_cloudflare_status_api(parsed):
    for site in parsed:
        # filter for the group
        if site["group_id"] == "1km35smx8p41" or site["group"] == 'True':
            yield Service(site["name"])


def check_cloudflare_status_api(item, params, parsed):
    # default to Unknown
    exit_code = 2
    # Notify if empty parsed input
    if parsed == []:
        yield 3, 'No pool data available'
    # Filter on the item passed and exit_code
    else:
        for site in parsed:
            if site["name"] == item:
                output = f'{site["name"]}'
                if site["status"] == "operational":
                    output += ' is fully operational.'
                    exit_code = 0
                elif site["status"] == "partial_outage":
                    output +=  ' is in a partial outage.'
                    exit_code = 1
                elif site["status"] == "degraded_performance":
                    output +=  ' is experiencing degraded performance.'
                    exit_code = 1
                else:
                    output +=  ' is in an unidentified or critical state.'
                    exit_code = 2
        yield exit_code, output, 'detailed output'


check_info['cloudflare_status_api'] = {
    'check_function': check_cloudflare_status_api,
    'inventory_function': discovery_cloudflare_status_api,
    'parse_function': parse_cloudflare_status_api,
    'service_description': 'Cloudflare Service %s',
    'has_perfdata': False,
    'group': 'cloudflare_status_api_group',
}
